const initialState = {"watson_results":"{\n  \"document_tone\": {\n    \"tone_categories\": [\n      {\n        \"tones\": [\n          {\n            \"score\": 0.138115,\n            \"tone_id\": \"anger\",\n            \"tone_name\": \"Anger\"\n          },\n          {\n            \"score\": 0.045574,\n            \"tone_id\": \"disgust\",\n            \"tone_name\": \"Disgust\"\n          },\n          {\n            \"score\": 0.364739,\n            \"tone_id\": \"fear\",\n            \"tone_name\": \"Fear\"\n          },\n          {\n            \"score\": 0.199981,\n            \"tone_id\": \"joy\",\n            \"tone_name\": \"Joy\"\n          },\n          {\n            \"score\": 0.191809,\n            \"tone_id\": \"sadness\",\n            \"tone_name\": \"Sadness\"\n          }\n        ],\n        \"category_id\": \"emotion_tone\",\n        \"category_name\": \"Emotion Tone\"\n      },\n      {\n        \"tones\": [\n          {\n            \"score\": 0,\n            \"tone_id\": \"analytical\",\n            \"tone_name\": \"Analytical\"\n          },\n          {\n            \"score\": 0,\n            \"tone_id\": \"confident\",\n            \"tone_name\": \"Confident\"\n          },\n          {\n            \"score\": 0,\n            \"tone_id\": \"tentative\",\n            \"tone_name\": \"Tentative\"\n          }\n        ],\n        \"category_id\": \"language_tone\",\n        \"category_name\": \"Language Tone\"\n      },\n      {\n        \"tones\": [\n          {\n            \"score\": 0.288614,\n            \"tone_id\": \"openness_big5\",\n            \"tone_name\": \"Openness\"\n          },\n          {\n            \"score\": 0.274434,\n            \"tone_id\": \"conscientiousness_big5\",\n            \"tone_name\": \"Conscientiousness\"\n          },\n          {\n            \"score\": 0.543323,\n            \"tone_id\": \"extraversion_big5\",\n            \"tone_name\": \"Extraversion\"\n          },\n          {\n            \"score\": 0.599483,\n            \"tone_id\": \"agreeableness_big5\",\n            \"tone_name\": \"Agreeableness\"\n          },\n          {\n            \"score\": 0.290953,\n            \"tone_id\": \"emotional_range_big5\",\n            \"tone_name\": \"Emotional Range\"\n          }\n        ],\n        \"category_id\": \"social_tone\",\n        \"category_name\": \"Social Tone\"\n      }\n    ]\n  }\n}","text":"testing 123","entry_type":"text","_id":"58f01132aabe45e9356c7fe0","tags":[],"audio":{"key":null,"bucket":null},"video":{"avg_data":null,"key":null,"bucket":null,"raw_data":null},"created_at":"2017-04-14T00:00:50.067Z"};

export default function(state = initialState, action) {
  // console.log('Action received active entry========', action);
  switch (action.type) {
  case 'ENTRY_SELECTED':
    return action.payload;
  }
  return state;
}
